version: "3"

services: 
    web:
        build: ./
        ports:
            - 3000:3000
        links:
            - db
        volumes:
            - .:/home/node/code
            - /home/node/code/node_modules
        environment:
            SECRET_TOKEN: esprivado
            MONGO_CONNECTION_STRING: mongodb://db:27017
    db:
        image: mongo:3